#!/bin/bash

#cpu_get=$(ps -eo pcpu,pid,user,args | sort -k 1 -r | head -10 | awk '{print $1}' | grep -P '[0-9]'  | awk '{ SUM += $1} END { print SUM}')
cpu_get=$(top -bn2 | grep '%Cpu' | tail -1 | grep -P '(....|...) id,'|awk '{print 100-$8 }')

echo "CPU: $cpu_get%"
