#!/bin/sh

hypr=$HOME/.config/hypr
wallpaper_folder=$hypr/wallpapers

wallpaper_location="$(ls $wallpaper_folder | wofi --show dmenu -W 340px -b --prompt Search...)"

$hypr/scripts/variables/set_env background "$wallpaper_folder/$wallpaper_location"

$hypr/scripts/background/wallpaper
